### PR TITLE
ja_jp.json

### PR DESCRIPTION
**Pull request by Ryuufa**
So sorry, I have never used github and don't know if this is the correct way to send files.

The Japanese localisation of Vanilla Minecraft uses phonetic transcription for the translation of proper nouns, so we did the same in the creation of this json file. Example:
Zombie → ゾンビ(zo n bi)
Piglin → ピグリン(pi gu ri n)
Grunt → グラント(gu ra n to)

### CODE REVIEW

**Comment by NumberSir** [comment]
1.0.4 was released already, I guess you need to change the branch to 1.0.5?

**Comment by Ryuufa** [comment]
@NumberSir 
okey, i did it.

**Comment by SoLegendary** [comment]
ok i've reworked how we're doing branches and releases so we can avoid having to rebase all the time
please rebase one more time to 1.19.2-dev and I will pull it in

**Comment by Ryuufa** [comment]
did it!

**Review by SoLegendary — APPROVED** [review]

**Pull request merged**
