### PR TITLE
Check for Passive, Change to Easy

### PR DESCRIPTION
**Pull request by ColinVaughn**
this simply just checks for passive, if passive it will change the mode to easy.

This will only work for single player as all servers would automatically be set to normal

### CODE REVIEW

**Comment by SoLegendary** [comment]
"Reign of Nether does not work with Passive, Mode set to Easy."
Please change this line to:
"RTS units cannot spawn in Peaceful. Your difficulty has been set to Easy."

Also please remove the teleport changes as I've just removed the ability for survival players to use F12 cam anyway

**Comment by ColinVaughn** [comment]
I think its still a good feature to have, its much nicer to be teleported
to ground level when leaving ortho than dropping to the ground from +40
above

**Comment by ColinVaughn** [comment]
I still think it's useful to teleport to the ground even given the fact thats it's impossible to die anymore

**Comment by SoLegendary** [comment]
If you're in creative or spectator you shouldn't fall anyway, your flying flag is always set to true when exiting F12.

**Comment by SoLegendary** [comment]
In any case, can you please separate this change from the peaceful -> easy change, because I would like to pull that one in

**Comment by ColinVaughn** [comment]
Removed teleporting to ground

**Review by SoLegendary — APPROVED** [review]

**Pull request merged**
