### PR TITLE
Translation Update (zh_cn)

### PR DESCRIPTION
**Pull request by Benzene114**
Latest additions of 1.0.10

### CODE REVIEW

**Comment by Benzene114** [comment]
I believe the check failure isn't on my end? Maven Metadata just happened to be inaccessible (site visit attempts returned a 504)

**Comment by IamAlittle** [comment]
> I believe the check failure isn't on my end? Maven Metadata just happened to be inaccessible (site visit attempts returned a 504)

Incorrect translation，Your text is completely AI translated

**Comment by SoLegendary** [comment]
I'm not worried about the build failures. However, there is a conflict now

**Comment by SoLegendary** [comment]
please resolve conflicts

**Pull request closed without merging**
