### PR TITLE
Create uk_ua

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SoLegendary** [comment]
Please sign the CLA.

Also, can you please sort the lines properly, many are all out of order.

**Comment by SoLegendary** [comment]
Also, the custom special characters have problems, eg:

`"buildings.monsters.reignofnether.pumpkin_farm.tooltip1": "  %d  +  %d  за кожний  посаджений гарбуз",`

This should be:

`"buildings.monsters.reignofnether.pumpkin_farm.tooltip1": "\uE001  %d  +  %d  за кожний  посаджений гарбуз",`

**Comment by ghost** [comment]
[SoLegendary](https://github.com/SoLegendary) done

**Comment by ghost** [comment]
I just transferred from webplate and it saved like that, but supposedly a wrong sorting won't make any errors

**Review by SoLegendary — APPROVED** [review]

**Pull request merged**
