### PR TITLE
Create `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**
Translated the `en_us.json`
I'm still not sure who `grunt` and `headhunter` are in the context of your mod. If these are piglins with swords and piglins with crossbows, respectively, then I guessed right.

### CODE REVIEW

**Comment by wixl22** [comment]
I think word "отряд" not really suits a unit, as it's only summon one creature.
So it's better to name it just
Призвать утопленника

**Comment by dimeetrue** [comment]
@mpustovoi , If I understood the author's intention correctly, then «grunt» translates as an infantryman «пехотинец»

**Comment by SoLegendary** [comment]
The piglins with tridents are called headhunters in English, but I think that bounty hunter is ok for name translation

**Comment by SoLegendary** [comment]
Can you please move to 1.19-1.0.4

**Comment by mpustovoi** [comment]
I guess I need to make a new PR, since I have forked only the default `1.19` and have no idea how to change it.

**Pull request closed without merging**
