### PR TITLE
Slightly Better Mod Compat

### PR DESCRIPTION
**Pull request by ColinVaughn**
This adds the use of tags to resources, also uses fixes snow rendering on the minimap, and adds speed buffs for walking on paths which I will be adding in the next pr.

### CODE REVIEW

**Comment by SoLegendary** [comment]
I know its a nitpick, sorry, but can you try avoiding formatting changes here?
Otherwise when I go back to touch the files I'll get the same diffs again

**Comment by SoLegendary** [comment]
Also I have a bit too much on the plate for 1.0.4, so I'll see if I can include this in 1.0.5, it does look good so far though

**Comment by ColinVaughn** [comment]
all good and I should have new pathfinding done for then

**Comment by SoLegendary** [comment]
Manually added the orthoviewclientevents and minimapclientevents, please refactor

**Pull request closed without merging**
